name: gains-trust
services:
  - name: backend
    source_dir: /Gains_Trust
    github:
      repo: dewi-afoko/Gains_Trust_Unchained
      branch: Live
    run_command: gunicorn --worker-tmp-dir /dev/shm Gains_Trust.wsgi:application
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
      - path: /admin
      - path: /static
    envs:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "REPLACE-WITH-YOUR-SECRET-KEY"
        type: SECRET
      - key: ALLOWED_HOSTS
        value: "*.ondigitalocean.app"
      - key: DATABASE_URL
        value: "${db.DATABASE_URL}"
      - key: EMAIL_HOST_USER
        value: "REPLACE-WITH-YOUR-EMAIL"
        type: SECRET
      - key: EMAIL_HOST_PASSWORD
        value: "REPLACE-WITH-APP-PASSWORD"
        type: SECRET
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: DEFAULT_FROM_EMAIL
        value: "REPLACE-WITH-YOUR-EMAIL"
      - key: PASSWORD_RESET_TIMEOUT
        value: "3600"

  - name: frontend
    source_dir: /frontend
    github:
      repo: your-username/Gains_Trust_Unchained
      branch: Live
    build_command: npm run build
    run_command: npx serve -s build -l ${PORT}
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: REACT_APP_API_BASE_URL
        value: ""

databases:
  - name: db
    engine: PG
    version: "13"
    size: basic-xs 