# Generated by Django 5.1.5 on 2025-02-06 16:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workout_name", models.CharField(max_length=255)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("complete", models.BooleanField(default=False)),
                ("user_weight", models.FloatField(blank=True, null=True)),
                ("sleep_score", models.IntegerField(blank=True, null=True)),
                ("sleep_quality", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SetDict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_name", models.CharField(max_length=255)),
                ("set_order", models.IntegerField(blank=True, null=True)),
                ("set_number", models.IntegerField(blank=True, null=True)),
                ("set_type", models.CharField(blank=True, max_length=100)),
                ("reps", models.IntegerField(blank=True, null=True)),
                ("focus", models.CharField(blank=True, max_length=150)),
                ("rest", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("complete", models.BooleanField(default=False)),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_dicts",
                        to="workouts.workout",
                    ),
                ),
            ],
        ),
    ]
