# Generated by Django 5.1.5 on 2025-02-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='setdict',
            name='loading',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
