# Generated by Django 5.1.5 on 2025-02-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_setdict_loading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
