# Generated by Django 5.1.5 on 2025-03-03 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0004_alter_workout_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="setdict",
            name="set_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="setdict",
            name="set_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workout",
            name="date",
            field=models.DateField(default=datetime.date(2025, 3, 3)),
        ),
    ]
