# Generated by Django 5.1.5 on 2025-03-03 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0005_setdict_set_duration_setdict_set_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 3, 3, 10, 49, 39, 125382, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
