# Generated by Django 5.1.5 on 2025-03-03 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0006_alter_workout_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
