# Generated by Django 5.1.5 on 2025-03-06 11:39

import workouts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0007_alter_workout_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="setdict",
            name="is_active_set",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="workout",
            name="date",
            field=models.DateField(default=workouts.models.get_today),
        ),
    ]
