# Generated by Django 5.1.5 on 2025-02-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userrecord_set_dict"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="previous_last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
