# Generated by Django 5.1.5 on 2025-02-17 13:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="previous_last_login",
        ),
        migrations.AddField(
            model_name="user",
            name="login_history",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateTimeField(), default=list, size=2
            ),
        ),
    ]
