# Generated by Django 5.1.5 on 2025-02-17 15:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_previous_last_login_user_login_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="login_history",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), default=list, size=2
            ),
        ),
    ]
