# Generated by Django 5.1.5 on 2025-02-17 15:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_login_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="login_history",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateTimeField(), default=list, size=None
            ),
        ),
    ]
