# Generated by Django 5.1.5 on 2025-06-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_passwordresettoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserRecord",
        ),
    ]
