# Generated by Django 5.1.5 on 2025-02-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_setdict_workout_remove_workout_user"),
        ("users", "0002_alter_userrecord_set_dict"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SetDict",
        ),
        migrations.DeleteModel(
            name="Workout",
        ),
    ]
