name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: dewi
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: gains_trust
          POSTGRES_HOST_AUTH_METHOD: trust # 🚀 Allows connections without a password
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U dewi" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r Gains_Trust/requirements.txt

      - name: Set Environment Variables
        run: |
          echo "DATABASE_URL=postgresql://dewi@localhost:5432/gains_trust" >> $GITHUB_ENV

      - name: Run Migrations
        run: |
          source venv/bin/activate
          cd Gains_Trust
          python manage.py migrate
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}

      - name: Run Tests
        run: |
          source venv/bin/activate
          cd Gains_Trust
          pytest --maxfail=5 --disable-warnings --cov=. --cov-report=term-missing
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
